version: '3.4'
services:
  db: 
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: springboot_project_login
    ports:
      - "3308:3306"
    networks:
      - springboot-project
  springboot-project-login:
    image: springboot-project-login
    restart: always
    build: ./springboot-project-login
    working_dir: /springboot-project-login
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
    - ./springboot-project-login:/springboot-project-login
    - ~/.m2:/root/.m2 
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - springboot-project
networks:
    springboot-project:
        driver: bridge
