CREATE TABLE IF NOT EXISTS person (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  address VARCHAR(100) NOT NULL,
  first_name VARCHAR(250) NOT NULL,
  gender VARCHAR(15) NOT NULL,
  last_name VARCHAR(80) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  password VARCHAR(50) NOT NULL,
  token VARCHAR(80) DEFAULT NULL
);
