CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  password VARCHAR(50) NOT NULL,
  token VARCHAR(80) DEFAULT NULL
);
